apiVersion: v2
name: github-issue-sync
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: common
  version: "0.6.3"
  repository: "https://paritytech.github.io/helm-charts/"

